AlphaCamp/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.AccessControl;
using System.Web;
using System.Web.Mvc;
using AlphaCamp.Models;
using Microsoft.AspNet.Identity;

namespace AlphaCamp.Controllers
{
    [Authorize]
    public class PeopleController : Controller
    {
        lonelyeAGTyCH6mBEntities db = new lonelyeAGTyCH6mBEntities();

        // GET: People
        public ActionResult Index()
        {
            var types = db.FoodTypes.ToList();
            var items = new List<SelectListItem>();
            foreach (var item in types)
            {
                items.Add(new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id
                });
            }
            ViewBag.foodTypes = items;
            return View();
        }

        [HttpPost]
        public ActionResult Index(Appointment model)
        {
            if (ModelState.IsValid)
            {
                model.Id = Guid.NewGuid().ToString().ToUpper();
                model.CreatTimeUtc = DateTime.UtcNow;
                if (User.Identity.IsAuthenticated)
                    model.CreaterId = User.Identity.GetUserId();
                db.Appointments.Add(model);
                db.SaveChanges();

                TempData["alert"] = "活動成功建立";
                return RedirectToAction("YesMan", new { id = model.Id });
            }

            var types = db.FoodTypes.ToList();
            var items = new List<SelectListItem>();
            foreach (var item in types)
            {
                items.Add(new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id
                });
            }
            ViewBag.foodTypes = items;

            string alert = string.Empty;
            foreach (ModelState modelState in ViewData.ModelState.Values) {
                foreach (ModelError error in modelState.Errors)
                {
                    alert += error.ErrorMessage + "<br/>";
                }
            }

            TempData["alert"] = alert;

            return View(model);
        }

        public ActionResult All()
        {
            return View();
        }

        public JsonResult GetAllAppointment()
        {
            var appoints = db.Appointments.AsQueryable();
            //string userId = User.Identity.GetUserId();
            //if (User.Identity.IsAuthenticated)
            //    appoints = appoints.Where(x => x.CreaterId != userId);
            var result = appoints.Select(x => new MapModel() { Id = x.Id, PeopleAmount = x.PeopleAmount, FoodTypes = x.FoodTypes, PriceRangeStart = x.PriceRangeStart, PriceRangeEnd = x.PriceRangeEnd, Name = x.Name, Latitude = x.Latitude, Longitude = x.Longitude, CreaterId = x.CreaterId, IsOver = x.IsOver }).Where(x => x.IsOver == false).ToList();
            if (!result.Any())
                return Json(new { status = "error", msg = "No data" }, JsonRequestBehavior.AllowGet);

            return Json(new { status = "success", data = result }, JsonRequestBehavior.AllowGet);
        }

        public class MapModel
        {
            public string Id { get; set; }
            public Nullable<int> PeopleAmount { get; set; }
            public string FoodTypes { get; set; }
            public Nullable<int> PriceRangeStart { get; set; }
            public Nullable<int> PriceRangeEnd { get; set; }
            public bool AllowAnonymous { get; set; }
            public Nullable<System.DateTime> CreatTimeUtc { get; set; }
            public Nullable<double> Latitude { get; set; }
            public Nullable<double> Longitude { get; set; }
            public string Name { get; set; }
            public string CreaterId { get; set; }
            public Nullable<System.DateTime> EatTime { get; set; }
            public bool IsOver { get; set; }
        }

        public ActionResult Detail(string id)
        {
            var data = db.Appointments.FirstOrDefault(x => x.Id == id);
            if (data == null)
                return HttpNotFound();

            string userId = User.Identity.GetUserId();
            if (String.Equals(userId, data.CreaterId, StringComparison.CurrentCultureIgnoreCase))
                return RedirectToAction("YesMan", new { id = data.Id });

            var accept = db.AppointmentAcceptions.FirstOrDefault(x => x.UserId == userId && x.AppointmentId == data.Id);
            if (accept != null)
                return RedirectToAction("YesMan", new { id = data.Id });

            int acceptCount = db.AppointmentAcceptions.Count(x => x.AppointmentId == data.Id) + 1;
            float acceptPersent = acceptCount / (float)data.PeopleAmount * 100;

            ViewBag.acceptCount = acceptCount;
            ViewBag.acceptPersent = acceptPersent;

            return View(data);
        }

        public ActionResult SayYes(string id)
        {
            var act = db.Appointments.FirstOrDefault(z => z.Id == id);
            if (act == null)
                return HttpNotFound();

            var acceptListCount = db.AppointmentAcceptions.Count(x => x.AppointmentId == act.Id);
            if (acceptListCount >= act.PeopleAmount - 1)
            {
                TempData["alert"] = "人數已滿";
                return RedirectToAction("Detail", new { id = act.Id });
            }

            var newAccept = new AppointmentAcception();
            newAccept.Id = Guid.NewGuid().ToString();
            newAccept.AppointmentId = act.Id;
            if (act.AllowAnonymous)
                newAccept.IsAccept = true;
            else
                newAccept.IsAccept = false;
            newAccept.CreatTimeUtc = DateTime.UtcNow;
            newAccept.UserId = User.Identity.GetUserId();
            db.AppointmentAcceptions.Add(newAccept);
            db.SaveChanges();

            return RedirectToAction("YesMan", new { id = act.Id });
        }

        public ActionResult YesMan(string id)
        {
            var act = db.Appointments.Include("AspNetUser").FirstOrDefault(z => z.Id == id);
            if (act == null)
                return HttpNotFound();

            string userId = User.Identity.GetUserId();
            if (userId.ToLower() != User.Identity.GetUserId().ToLower())
            {
                var accept =
                    db.AppointmentAcceptions.FirstOrDefault(x => x.UserId == userId && x.AppointmentId == act.Id);
                if (accept == null)
                    return HttpNotFound();
                if (userId != accept.UserId)
                    return HttpNotFound();
            }

            var acceptList = db.AppointmentAcceptions.Include("AspNetUser").Where(x => x.AppointmentId == act.Id).ToList();
            ViewBag.acceptList = acceptList;

            int acceptCount = db.AppointmentAcceptions.Count(x => x.AppointmentId == act.Id) + 1;
            float acceptPersent = acceptCount / (float)act.PeopleAmount * 100;

            ViewBag.acceptCount = acceptCount;
            ViewBag.acceptPersent = acceptPersent;

            return View(act);
        }

        public ActionResult RemoveAcception(string id)
        {
            var accept = db.AppointmentAcceptions.FirstOrDefault(x => x.Id == id);
            if (accept == null)
                return HttpNotFound();

            var act = db.Appointments.FirstOrDefault(x => x.Id == accept.AppointmentId);
            if (act == null)
                return HttpNotFound();

            db.AppointmentAcceptions.Remove(accept);
            db.SaveChanges();

            return RedirectToAction("YesMan", new { id = act.Id });
        }

        public ActionResult SayBye(string id)
        {
            var act = db.Appointments.FirstOrDefault(x => x.Id == id);
            if (act == null)
                return HttpNotFound();

            db.Entry(act).State = EntityState.Modified;
            act.IsOver = true;
            db.SaveChanges();

            return RedirectToAction("YesMan", new { id = act.Id });
        }

        public ActionResult SayGo(string id)
        {
            var act = db.Appointments.FirstOrDefault(x => x.Id == id);
            if (act == null)
                return HttpNotFound();

            db.Entry(act).State = EntityState.Modified;
            act.IsOver = true;
            act.IsGo = true;
            db.SaveChanges();

            return RedirectToAction("YesMan", new { id = act.Id });
        }
    }
}

AlphaCamp/Views/People/All.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "All";
}

<h2>All</h2>

<div id="mapholder"></div>

@section scripts
{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/bootstrap-switch/bootstrap3/bootstrap-switch.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="~/Scripts/bootbox.js"></script>
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script src="~/Scripts/bootstrap-switch.js"></script>
    <script>
        // Beautify
        $("[type='checkbox']").bootstrapSwitch('state', true, true);
        $('.selectpicker').selectpicker();

        // Geo
        getLocation();

        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition, showError);
            } else {
                bootbox.alert("Geolocation is not supported by this browser.");
            }
        }

        function showPosition(position) {
            var lat = position.coords.latitude;
            var lon = position.coords.longitude;
            var latlon = new google.maps.LatLng(lat, lon);
            var mapholder = document.getElementById('mapholder');
            mapholder.style.height = '450px';
            mapholder.style.width = '100%';

            var myOptions = {
                center: latlon,
                zoom: 15,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                mapTypeControl: false,
                navigationControlOptions: { style: google.maps.NavigationControlStyle.SMALL }
            };
            var map = new google.maps.Map(document.getElementById("mapholder"), myOptions);


            // Load relative appointment
            $.ajax({
                url: '@Url.Action("GetAllAppointment")',
                method: 'GET',
                dataType: 'json',
                success: function (result) {
                    if (result.status == "success") {
                        for (var count in result.data) {
                            var item = result.data[count];
                            var latLng = new google.maps.LatLng(item.Latitude, item.Longitude);
                            // Creating a marker and putting it on the map
                            var marker = new google.maps.Marker({
                                position: latLng,
                                map: map,
                                animation: google.maps.Animation.DROP,
                                title: item.title
                            });
                            if (item.CreaterId != '@User.Identity.GetUserId()')
                                marker.setIcon('http://maps.google.com/mapfiles/ms/icons/green-dot.png');
                            var infowindow = new google.maps.InfoWindow({
                                content: item.Name
                            });
                            bindInfoWindow(marker, map, infowindow, item.Name);
                            infowindow.open(map, marker);
                        }
                    } else {
                        bootbox.alert(result.msg);
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.status);
                    alert(thrownError);
                }
            });

            //var infowindow = new google.maps.InfoWindow({
            //    content: "test",
            //    maxWidth: 200
            //});
            //var marker = new google.maps.Marker({ position: latlon, map: map, title: "You are here!" });
            //google.maps.event.addListener(marker, 'click', function () {
            //    infowindow.open(map, marker);
            //});
        }

        function bindInfoWindow(marker, map, infowindow, strDescription) {
            google.maps.event.addListener(marker, 'click', function () {
                infowindow.setContent(strDescription);
                infowindow.open(map, marker);
            });
        }

        function showError(error) {
            switch (error.code) {
                case error.PERMISSION_DENIED:
                    bootbox.alert("User denied the request for Geolocation.");
                    break;
                case error.POSITION_UNAVAILABLE:
                    bootbox.alert("Location information is unavailable.");
                    break;
                case error.TIMEOUT:
                    bootbox.alert("The request to get user location timed out.");
                    break;
                case error.UNKNOWN_ERROR:
                    bootbox.alert("An unknown error occurred.");
                    break;
            }
        }
    </script>
}

AlphaCamp/Views/People/Detail.cshtml
@model AlphaCamp.Models.Appointment

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            團名(活動名稱)：
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            揪團者：
        </dt>

        <dd>
            @Model.AspNetUser.UserName
        </dd>

        <dt>
            成團人數：
        </dt>

        <dd>
            @(ViewBag.acceptCount + " / " + Model.PeopleAmount)
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@ViewBag.acceptPersent" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: @ViewBag.acceptPersent%;">
                    @ViewBag.acceptPersent% 滿員
                </div>
            </div>
        </dd>

        <dt>
            討伐目標：
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodTypes)
        </dd>

        <dt>
            口袋深度：
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceRangeStart)
            ~
            @Html.DisplayFor(model => model.PriceRangeEnd)
        </dd>

        <dt>
            是否徵求有緣人：
        </dt>

        <dd>
            @if (Model.AllowAnonymous)
            {
                <text>是</text>
            }
            else
            {
                <text>否</text>
            }
        </dd>

        <dt>
            出征時間：
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EatTime)
        </dd>

    </dl>
</div>
<p>
    @if (ViewBag.acceptCount < Model.PeopleAmount)
    {
        @Html.ActionLink("一起聚餐", "SayYes", new { id = Model.Id }, new { @class = "btn btn-lg btn-primary" })
        @Html.ActionLink("看別的", "Index", null, new { @class = "btn btn-lg btn-default" })
    }
    else
    {
        @Html.ActionLink("此團已滿員，看別的", "Index", null, new { @class = "btn btn-lg btn-default" })
    }
</p>

@section scripts{
    <script src="~/Scripts/bootbox.js"></script>
    @if (TempData["alert"] != null && !string.IsNullOrWhiteSpace(TempData["alert"].ToString()))
    {
        <script>
            bootbox.alert("@TempData["alert"].ToString()");
        </script>
    }
}

AlphaCamp/Views/People/Index.cshtml
@using System.Collections.Concurrent
@using Microsoft.AspNet.Identity
@model AlphaCamp.Models.Appointment
@{
    ViewBag.Title = "Index";
}

<style>
    #base {
        float: left;
        width: 100%;
        height: 180px;
    }

    #mapholder {
        float: left;
        width: 70%;
        height: 450px;
    }

    #right {
        width: 30%;
        height: 180px;
        float: right;
    }

    ul {
        list-style-type: none;
    }
</style>



<h2>Index</h2>

<div id="base">
    <div id="mapholder"></div>
    <div id="right">
        開團：
        @using (Html.BeginForm("Index", "People", FormMethod.Post, new { id = "form1" }))
        {
            <ul>
                <li>
                    團名(活動名稱)：
                    <input type="text" name="Name" value="" class="form-control" />
                </li>
                <li>
                    <br />
                    成團人數：
                    <input type="number" name="PeopleAmount" value="" class="form-control" />
                </li>
                <li>
                    <br />
                    討伐目標：
                    @Html.DropDownList("FoodTypes", (IEnumerable<SelectListItem>)ViewBag.foodTypes, new { @class = "form-control" })
                </li>
                <li>
                    <br />
                    口袋深度：
                    <input type="number" name="PriceRangeStart" value="" class="form-control" />
                    ~
                    <br />
                    <input type="number" name="PriceRangeEnd" value="" class="form-control" />
                </li>
                <li>
                    <br />
                    吃飯時間:
                    <div class='input-group date' id='datetimepicker2'>
                        <input type="datetime" name="EatTime" value="" class="form-control datetimepicker" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </li>
                <li>
                    <br />
                    是否徵求有緣人：
                    @Html.CheckBox("AllowAnonymous", new { data_on_text = "Yes", data_off_text = "No" })
                </li>
                <li>
                    <br />
                    <a href="javascript:void(0);" onclick=" sendWithLocation(this.form); " class="btn btn-primary">Submit</a>
                </li>
            </ul>
            <input type="hidden" id="Longitude" name="Longitude" value="" />
            <input type="hidden" id="Latitude" name="Latitude" value="" />
        }
    </div>
</div>

@section scripts{
    <link href="~/Content/bootstrap-switch/bootstrap3/bootstrap-switch.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <script src="~/Scripts/moment-with-locales.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="~/Scripts/bootbox.js"></script>
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script src="~/Scripts/bootstrap-switch.js"></script>
    <script>
        // Beautify
        $("[type='checkbox']").bootstrapSwitch('state', true, true);
        $('.selectpicker').selectpicker();
        $('.datetimepicker').datetimepicker({
            locale: 'en',
            format: 'YYYY/MM/DD HH:mm'
        });

        // submit with location
        function sendWithLocation(form) {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(submitForm, showError);
            } else {
                bootbox.alert("Geolocation is not supported by this browser.");
            }
            from1 = form;
        }

        function submitForm(position) {
            var lat = position.coords.latitude;
            var lon = position.coords.longitude;
            var latlon = new google.maps.LatLng(lat, lon);

            $("#Latitude").val(lat);
            $("#Longitude").val(lon);

            form1.submit();
        }

        // Geo
        getLocation();

        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition, showError);
            } else {
                bootbox.alert("Geolocation is not supported by this browser.");
            }
        }

        function showPosition(position) {
            var lat = position.coords.latitude;
            var lon = position.coords.longitude;
            var latlon = new google.maps.LatLng(lat, lon);
            console.log("google latlon" + latlon);
            var mapholder = document.getElementById('mapholder');
            //mapholder.style.height = '450px';
            //mapholder.style.width = '100%';

            var myOptions = {
                center: latlon,
                zoom: 15,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                mapTypeControl: false,
                navigationControlOptions: { style: google.maps.NavigationControlStyle.SMALL }
            };
            var map = new google.maps.Map(document.getElementById("mapholder"), myOptions);
            var tmarker = new google.maps.Marker({ position: latlon, map: map, title: "You are here!" });
            var tinfowindow = new google.maps.InfoWindow({
                content: "I'm Here."
            });
            bindInfoWindow(tmarker, map, tinfowindow, "I'm Here.");
            tinfowindow.open(map, tmarker);

            $.ajax({
                url: '@Url.Action("GetAllAppointment")',
                method: 'GET',
                dataType: 'json',
                success: function (result) {
                    if (result.status == "success") {
                        for (var count in result.data) {
                            var item = result.data[count];
                            var latLng = new google.maps.LatLng(item.Latitude, item.Longitude);
                            // Creating a marker and putting it on the map
                            var marker = new google.maps.Marker({
                                position: latLng,
                                map: map,
                                animation: google.maps.Animation.DROP,
                                title: item.title
                            });
                            if (item.CreaterId != '@User.Identity.GetUserId()')
                                marker.setIcon('http://maps.google.com/mapfiles/ms/icons/green-dot.png');
                            var infowindow = new google.maps.InfoWindow({
                                content: "<div><h1>" + item.Name + "</h1>" + "<a href='@Url.Action("Detail")/" + item.Id + "'>前往觀看</a></div>"
                            });
                            var ccontent = "<div><h4>" + item.Name + "</h4>" + "<a href='@Url.Action("Detail")/" + item.Id + "'>前往觀看</a></div>";
                            bindInfoWindow(marker, map, infowindow, ccontent);
                        }
                    } else {
                        bootbox.alert(result.msg);
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(xhr.status);
                    alert(thrownError);
                }
            });
        }

        function bindInfoWindow(marker, map, infowindow, strDescription) {
            google.maps.event.addListener(marker, 'click', function () {
                infowindow.setContent(strDescription);
                infowindow.open(map, marker);
            });
        }

        function showError(error) {
            switch (error.code) {
                case error.PERMISSION_DENIED:
                    bootbox.alert("User denied the request for Geolocation.");
                    break;
                case error.POSITION_UNAVAILABLE:
                    bootbox.alert("Location information is unavailable.");
                    break;
                case error.TIMEOUT:
                    bootbox.alert("The request to get user location timed out.");
                    break;
                case error.UNKNOWN_ERROR:
                    bootbox.alert("An unknown error occurred.");
                    break;
            }
        }
    </script>
}

AlphaCamp/Views/People/YesMan.cshtml
@using AlphaCamp.Models
@using Microsoft.AspNet.Identity
@model AlphaCamp.Models.Appointment

@{
    ViewBag.Title = "YesMan";
}

<h2>YesMan</h2>
<div>
    @if (!Model.IsOver)
    {
        <h3><span class="label label-success">開團徵求勇者中</span></h3>
    }
    else
    {
        if (Model.IsGo)
        {
            <h3><span class="label label-info">已出團</span></h3>
        }
        else
        {
            <h3><span class="label label-danger">已滅團</span></h3>
        }
    }
</div>
<div>
    @if (User.Identity.GetUserId().ToLower().Equals(Model.CreaterId.ToLower()))
    {
        <a href="@Url.Action("SayGo", new { id = Model.Id })"><span class="glyphicon glyphicon-ok btn btn-default" aria-hidden="true">立即開團</span></a>
        <text>&nbsp;&nbsp;</text>
        <a href="@Url.Action("SayBye", new { id = Model.Id })"><span class="glyphicon glyphicon-remove btn btn-default" aria-hidden="true">宣告流團</span></a>
    }
</div>
<div>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                團名(活動名稱)：
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                揪團者：
            </dt>

            <dd>
                @Model.AspNetUser.UserName
            </dd>

            <dt>
                成團人數：
            </dt>

            <dd>
                @(ViewBag.acceptCount + " / " + Model.PeopleAmount)
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="@ViewBag.acceptPersent" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: @ViewBag.acceptPersent%;">
                        @ViewBag.acceptPersent% 滿員
                    </div>
                </div>
            </dd>

            <dt>
                討伐目標：
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FoodTypes)
            </dd>

            <dt>
                口袋深度：
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PriceRangeStart)
                ~
                @Html.DisplayFor(model => model.PriceRangeEnd)
            </dd>

            <dt>
                是否徵求有緣人：
            </dt>

            <dd>
                @if (Model.AllowAnonymous)
                {
                    <text>是</text>
                }
                else
                {
                    <text>否</text>
                }
            </dd>

            <dt>
                出征時間：
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EatTime)
            </dd>

        </dl>
    </div>
    <div>
        參與者
        <table class="table table-striped table-hover">
            <tr>
                <td>編號</td>
                <td width="150">身分</td>
                <td>暱稱</td>
                @if (User.Identity.GetUserId().ToLower().Equals(Model.CreaterId.ToLower()))
                {
                    <td>控制</td>
                }
            </tr>
            <tr>
                <td>1.</td>
                <td>主辦</td>
                <td>@Model.AspNetUser.UserName</td>
                <td></td>
            </tr>
            @{int i = 2;}
            @foreach (AppointmentAcception item in ViewBag.acceptList)
            {
                <tr>
                    <td>@i</td>
                    <td>參與者</td>
                    <td>@item.AspNetUser.UserName</td>
                    @if (User.Identity.GetUserId().ToLower().Equals(Model.CreaterId.ToLower()))
                    {
                        <td>
                            <a href="@Url.Action("RemoveAcception", new { id = item.Id })" class="btn btn-danger">把他踢掉</a>
                        </td>
                    }
                </tr>
                    i++;
            }
        </table>
    </div>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

@section scripts{
    <script src="~/Scripts/bootbox.js"></script>
    @if (TempData["alert"] != null && !string.IsNullOrWhiteSpace(TempData["alert"].ToString()))
    {
        <script>
            bootbox.alert("@TempData["alert"].ToString()");
        </script>
    }
}